PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
PRAGMA synchronous = NORMAL;

CREATE TABLE IF NOT EXISTS FILE_HASH_INDEX (
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    FILE_PATH             TEXT    NOT NULL,
    FILE_NAME             TEXT    NOT NULL,
    FILE_SIZE             INTEGER NOT NULL,
    FILE_MODIFICATION_TS  TEXT    NOT NULL,
    SHA256_HASH           TEXT    NOT NULL,
    MEDIA_DATE            TEXT,
    CREATED_AT            TEXT    NOT NULL,
    LAST_PROCESSED_AT     TEXT    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_hash_sha256
    ON FILE_HASH_INDEX(SHA256_HASH);

CREATE INDEX IF NOT EXISTS idx_hash_filepath
    ON FILE_HASH_INDEX(FILE_PATH);

CREATE TABLE IF NOT EXISTS JOB_STATISTICS (
    JOB_ID                TEXT    PRIMARY KEY,
    STATUS                TEXT    NOT NULL DEFAULT 'RUNNING',
    START_TIME            TEXT    NOT NULL,
    END_TIME              TEXT,
    FILES_PROCESSED       INTEGER NOT NULL DEFAULT 0,
    FILES_FAILED          INTEGER NOT NULL DEFAULT 0,
    FILES_SKIPPED         INTEGER NOT NULL DEFAULT 0,
    DUPLICATES_FOUND      INTEGER NOT NULL DEFAULT 0,
    FILES_COPIED          INTEGER NOT NULL DEFAULT 0,
    FILES_MOVED           INTEGER NOT NULL DEFAULT 0,
    EMPTY_FILES_COUNT     INTEGER NOT NULL DEFAULT 0,
    SMALL_FILES_COUNT     INTEGER NOT NULL DEFAULT 0,
    CORRUPT_FILES_COUNT   INTEGER NOT NULL DEFAULT 0,
    TOTAL_BYTES_PROCESSED INTEGER NOT NULL DEFAULT 0,
    TOTAL_BYTES_MOVED     INTEGER NOT NULL DEFAULT 0,
    TOTAL_BYTES_COPIED    INTEGER NOT NULL DEFAULT 0,
    TOTAL_BYTES_SKIPPED   INTEGER NOT NULL DEFAULT 0,
    DUPLICATE_BYTE_SAVINGS INTEGER NOT NULL DEFAULT 0,
    TOTAL_FOLDERS_CREATED INTEGER NOT NULL DEFAULT 0,
    AVG_MB_PER_SEC        REAL    NOT NULL DEFAULT 0,
    PEAK_MB_PER_SEC       REAL    NOT NULL DEFAULT 0,
    AVG_FILES_PER_SEC     REAL    NOT NULL DEFAULT 0,
    PEAK_FILES_PER_SEC    REAL    NOT NULL DEFAULT 0,
    AVG_CPU_PERCENT       REAL    NOT NULL DEFAULT 0,
    PEAK_CPU_PERCENT      REAL    NOT NULL DEFAULT 0,
    AVG_MEMORY_GB         REAL    NOT NULL DEFAULT 0,
    PEAK_MEMORY_GB        REAL    NOT NULL DEFAULT 0
);

PRAGMA user_version = 1;
